name: facenet
channels:
  - c4aarch64
  - conda-forge
  - https://conda.anaconda.org/c4aarch64
  - https://conda.anaconda.org/conda-forge
dependencies:
  - gettext=0.19.8.1=h7b6447c_3
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.7.2=h4e544f5_0
  - aom=3.3.0=headf329_1
  - bzip2=1.0.8=hf897c2e_4
  - c-ares=1.18.1=hf897c2e_0
  - ca-certificates=2022.9.24=h4fd8a4c_0
  - cairo=1.16.0=h007064d_1010
  - dbus=1.13.6=h12b9eeb_3
  - expat=2.5.0=ha18d298_0
  - ffmpeg=4.4.1=h6e4b094_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h77febde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=h01db608_1
  - freetype=2.12.1=hbbbf32d_0
  - glib=2.74.0=h7866ba4_0
  - glib-tools=2.74.0=h7866ba4_0
  - gmp=6.2.1=h7fd3ca4_0
  - gnutls=3.6.13=h5fb5790_1
  - graphite2=1.3.13=h7fd3ca4_1001
  - gst-plugins-base=1.20.3=h9c4ba4c_2
  - gstreamer=1.20.3=hf4e84e4_2
  - harfbuzz=4.2.0=hefe178f_0
  - hdf5=1.12.1=nompi_h3900512_104
  - icu=69.1=h3621d8e_0
  - jasper=2.0.33=h5ced176_0
  - jpeg=9e=h9cdd2b7_2
  - keyutils=1.6.1=h4e544f5_0
  - krb5=1.19.3=h750e270_0
  - lame=3.100=h4e544f5_1003
  - ld_impl_linux-aarch64=2.39=ha75b1e8_0
  - lerc=4.0.0=h4de3ea5_0
  - libblas=3.9.0=16_linuxaarch64_openblas
  - libcblas=3.9.0=16_linuxaarch64_openblas
  - libclang=13.0.1=default_hf9dac01_0
  - libcurl=7.86.0=h22f3f83_1
  - libdeflate=1.14=h4e544f5_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h4f30969_4
  - libffi=3.4.2=h3557bc0_5
  - libgcc-ng=12.2.0=h607ecd0_19
  - libgfortran-ng=12.2.0=he9431aa_19
  - libgfortran5=12.2.0=hf695500_19
  - libglib=2.74.0=h58953e2_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=12.2.0=h607ecd0_19
  - libiconv=1.17=h9cdd2b7_0
  - liblapack=3.9.0=16_linuxaarch64_openblas
  - liblapacke=3.9.0=16_linuxaarch64_openblas
  - libllvm13=13.0.1=hb2805f8_2
  - libnghttp2=1.47.0=h674c3cc_1
  - libnsl=2.0.0=hf897c2e_0
  - libogg=1.3.4=h3557bc0_1
  - libopenblas=0.3.21=pthreads_h6cb6f83_3
  - libopencv=4.5.5=py310hc2e78f4_10
  - libopus=1.3.1=hf897c2e_1
  - libpng=1.6.38=hf9034f9_0
  - libpq=14.5=h2856e3f_1
  - libprotobuf=3.20.2=h4dffa80_0
  - libsqlite=3.40.0=hf9034f9_0
  - libssh2=1.10.0=he5a64b1_3
  - libstdcxx-ng=12.2.0=hc13a102_19
  - libtiff=4.4.0=hacef7f3_4
  - libuuid=2.32.1=hf897c2e_1000
  - libvorbis=1.3.7=h01db608_0
  - libvpx=1.11.0=h01db608_3
  - libwebp-base=1.2.4=h4e544f5_0
  - libxcb=1.13=h3557bc0_1004
  - libxkbcommon=1.0.3=he09c752_0
  - libxml2=2.9.12=h1e2ce75_1
  - libzlib=1.2.13=h4e544f5_4
  - mysql-common=8.0.31=h224b56f_0
  - mysql-libs=8.0.31=h8735f6a_0
  - ncurses=6.3=headf329_1
  - nettle=3.6=ha0d5d3d_0
  - nspr=4.32=h01db608_0
  - nss=3.78=h1b46d77_0
  - numpy=1.23.4=py310he617cf3_1
  - opencv=4.5.5=py310hbbe02a8_10
  - openh264=2.1.1=h469bdbd_0
  - openssl=3.0.7=h4e544f5_0
  - pcre2=10.37=he7b27c6_1
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=hb9de7d4_0
  - pthread-stubs=0.4=hb9de7d4_1001
  - py-opencv=4.5.5=py310h7d5ade6_10
  - python=3.10.6=h92ab765_0_cpython
  - python_abi=3.10=2_cp310
  - qt=5.12.9=hd3f9f3d_6
  - readline=8.1.2=h38e3740_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sqlite=3.40.0=h69ca7e5_0
  - svt-av1=0.9.1=h4de3ea5_0
  - tk=8.6.12=hd8af866_0
  - tzdata=2022f=h191b570_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - x264=1!161.3030=hf897c2e_1
  - x265=3.5=hdd96247_3
  - xorg-fixesproto=5.0=h3557bc0_1002
  - xorg-inputproto=2.3.2=h3557bc0_1002
  - xorg-kbproto=1.0.7=h3557bc0_1002
  - xorg-libice=1.0.10=h3557bc0_0
  - xorg-libsm=1.2.3=h965e137_1000
  - xorg-libx11=1.7.2=h3557bc0_0
  - xorg-libxau=1.0.9=h3557bc0_0
  - xorg-libxdmcp=1.1.3=h3557bc0_0
  - xorg-libxext=1.3.4=h3557bc0_1
  - xorg-libxfixes=5.0.3=h3557bc0_1004
  - xorg-libxi=1.7.10=h3557bc0_0
  - xorg-libxrender=0.9.10=h3557bc0_1003
  - xorg-renderproto=0.11.1=h3557bc0_1002
  - xorg-xextproto=7.3.0=h3557bc0_1002
  - xorg-xproto=7.0.31=h3557bc0_1007
  - xz=5.2.6=h9cdd2b7_0
  - zlib=1.2.13=h4e544f5_4
  - zstd=1.5.2=hc1e27d5_4
  - pip:
    - certifi==2025.10.5
    - charset-normalizer==3.4.4
    - coloredlogs==15.0.1
    - facenet-pytorch==2.6.0
    - filelock==3.20.0
    - flatbuffers==25.9.23
    - fsspec==2025.9.0
    - humanfriendly==10.0
    - idna==3.11
    - jinja2==3.1.6
    - kagglehub==0.3.13
    - mako==1.3.10
    - markdown-it-py==4.0.0
    - markupsafe==3.0.3
    - mdurl==0.1.2
    - ml_dtypes==0.5.3
    - mpmath==1.3.0
    - networkx==3.4.2
    - onnx==1.19.1
    - onnxruntime==1.23.2
    - onnxsim==0.4.36
    - opencv-python==4.12.0.88
    - packaging==25.0
    - pillow==10.2.0
    - platformdirs==4.5.0
    - protobuf==6.33.0
    - pycuda==2025.1.2
    - pygments==2.19.2
    - pytools==2025.2.5
    - pyyaml==6.0.3
    - requests==2.32.5
    - rich==14.2.0
    - siphash24==1.8
    - sympy==1.14.0
    - torch==2.2.2
    - torchvision==0.17.2
    - tqdm==4.67.1
    - typing_extensions==4.15.0
    - urllib3==2.5.0
prefix: /home/ntu/archiconda3/envs/facenet

